# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exampledb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exampledb.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x65xampledb.proto\"\xa1\x01\n\x07\x45xample\x12\x0f\n\x07\x63hinese\x18\x01 \x01(\t\x12\x0f\n\x07\x65nglish\x18\x02 \x01(\t\x12\x1f\n\x06source\x18\x03 \x01(\x0e\x32\x0f.Example.Source\x12\x12\n\ncreated_ts\x18\x04 \x01(\x01\"?\n\x06Source\x12\t\n\x05ICIBA\x10\x00\x12\x0c\n\x08LINEDICT\x10\x01\x12\x10\n\x0cYELLOWBRIDGE\x10\x02\x12\n\n\x06MANUAL\x10\x03\"5\n\tWordEntry\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x1a\n\x08\x65xamples\x18\x02 \x03(\x0b\x32\x08.Example')
)



_EXAMPLE_SOURCE = _descriptor.EnumDescriptor(
  name='Source',
  full_name='Example.Source',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ICIBA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINEDICT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOWBRIDGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_EXAMPLE_SOURCE)


_EXAMPLE = _descriptor.Descriptor(
  name='Example',
  full_name='Example',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chinese', full_name='Example.chinese', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='english', full_name='Example.english', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='Example.source', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_ts', full_name='Example.created_ts', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXAMPLE_SOURCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=181,
)


_WORDENTRY = _descriptor.Descriptor(
  name='WordEntry',
  full_name='WordEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='WordEntry.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examples', full_name='WordEntry.examples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=236,
)

_EXAMPLE.fields_by_name['source'].enum_type = _EXAMPLE_SOURCE
_EXAMPLE_SOURCE.containing_type = _EXAMPLE
_WORDENTRY.fields_by_name['examples'].message_type = _EXAMPLE
DESCRIPTOR.message_types_by_name['Example'] = _EXAMPLE
DESCRIPTOR.message_types_by_name['WordEntry'] = _WORDENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Example = _reflection.GeneratedProtocolMessageType('Example', (_message.Message,), dict(
  DESCRIPTOR = _EXAMPLE,
  __module__ = 'exampledb_pb2'
  # @@protoc_insertion_point(class_scope:Example)
  ))
_sym_db.RegisterMessage(Example)

WordEntry = _reflection.GeneratedProtocolMessageType('WordEntry', (_message.Message,), dict(
  DESCRIPTOR = _WORDENTRY,
  __module__ = 'exampledb_pb2'
  # @@protoc_insertion_point(class_scope:WordEntry)
  ))
_sym_db.RegisterMessage(WordEntry)


# @@protoc_insertion_point(module_scope)
